"""
This file runs all the unit tests. Run this to make sure at least the functions tested are working as they're supposed
to.
"""

from neural_util_test import * # Do not delete these imports...
from general_util_test import * # Do not delete these imports...
from conv_util_test import * # Do not delete these imports...
from adv_net_util_test import * # Do not delete these imports...
from colorful_img_network_util_test import * # Do not delete these imports...
# from sketches_util_test import * # Do not delete these imports...
from unet_util_test import * # Do not delete these imports...
import unittest

# Not importing the following util test because it will require human input to verify the effect of the function.
# from sketches_util_test import *

if __name__ == '__main__':
    unittest.main()